import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { useForm, type FieldErrors } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { CalendarCheck, Edit2, Plus, Trash2 } from 'lucide-react'
import { Alert, Badge, Button, ConfirmDialog, DataTable, Field, FilterBar, Input, Modal, PageHeader, Pagination, Select, toast, type DataTableColumn } from '@/components/ui'
import { useBranch } from '@/app/providers/branch-context'
import { ApiError } from '@/infrastructure/http'
import { agendaApi } from '@/features/agenda/agenda.api'
import { appointmentSchema } from '@/features/agenda/agenda.schemas'
import type { Appointment, AppointmentStatus } from '@/features/agenda/agenda.models'
import { z } from 'zod'
const errorText = (error: unknown) => error instanceof ApiError ? error.messages.join(' ') : error instanceof Error ? error.message : 'No fue posible completar la operación.'
const statusOptions: Array<[AppointmentStatus, string]> = [['SCHEDULED', 'Programada'], ['CONFIRMED', 'Confirmada'], ['CHECKED_IN', 'Registrada'], ['IN_PROGRESS', 'En consulta'], ['COMPLETED', 'Completada'], ['CANCELLED', 'Cancelada'], ['NO_SHOW', 'No asistió']]
const statusLabel = (value: string) => statusOptions.find(([key]) => key === value)?.[1] ?? value
const actionLabels: Record<string, string> = { confirm: 'Confirmar', 'check-in': 'Check-in', start: 'Iniciar', complete: 'Completar', 'no-show': 'No asistió' }
const statusVariant = (value: string): 'success' | 'warning' | 'neutral' | 'danger' => value === 'COMPLETED' || value === 'CONFIRMED' ? 'success' : value === 'CANCELLED' || value === 'NO_SHOW' ? 'danger' : value === 'IN_PROGRESS' || value === 'CHECKED_IN' ? 'warning' : 'neutral'
const formSchema = appointmentSchema.extend({ status: z.string().optional() })
type FormValues = Record<string, string>
const getError = (errors: FieldErrors<FormValues>, name: string) => errors[name]?.message?.toString()
function AppointmentForm({ values, error, onSubmit }: { values: FormValues; error: string | null; onSubmit: (values: FormValues) => Promise<void> }) {
  const { register, handleSubmit, formState: { errors } } = useForm<FormValues>({ defaultValues: values, resolver: zodResolver(formSchema) as never })
  const fields = [['patientId', 'ID de paciente', 'number'], ['scheduleId', 'ID de agenda', 'number'], ['healthProfessionalId', 'ID de profesional', 'number'], ['serviceId', 'ID de servicio', 'number'], ['branchId', 'ID de sucursal', 'number'], ['consultingRoomId', 'ID de consultorio', 'number'], ['startAt', 'Inicio', 'datetime-local'], ['endAt', 'Fin', 'datetime-local']] as const
  return <form id="appointment-form" className="grid gap-4 sm:grid-cols-2" onSubmit={handleSubmit(onSubmit)} noValidate>{error && <Alert className="sm:col-span-2" variant="danger" title="No se pudo guardar">{error}</Alert>}{fields.map(([name, label, type]) => <Field key={name} label={label} htmlFor={`appointment-${name}`} required={name !== 'consultingRoomId'} error={getError(errors, name)}><Input id={`appointment-${name}`} type={type} error={Boolean(getError(errors, name))} {...register(name)} /></Field>)}<Field label="Motivo" htmlFor="appointment-reasonForVisit"><Input id="appointment-reasonForVisit" {...register('reasonForVisit')} /></Field><Field label="Notas" htmlFor="appointment-notes"><Input id="appointment-notes" {...register('notes')} /></Field></form>
}
export default function AppointmentsPage() {
  const { can } = useBranch(); const client = useQueryClient(); const [page, setPage] = useState(1); const [filters, setFilters] = useState<FormValues>({}); const [draft, setDraft] = useState<FormValues>({}); const [editing, setEditing] = useState<Appointment | null>(null); const [formOpen, setFormOpen] = useState(false); const [formError, setFormError] = useState<string | null>(null); const [removing, setRemoving] = useState<Appointment | null>(null)
  const query = useQuery({ queryKey: ['appointments', page, filters], queryFn: () => agendaApi.appointments.list({ page, limit: 10, ...filters }), enabled: can('appointments.read') }); const create = useMutation({ mutationFn: agendaApi.appointments.create, onSuccess: () => client.invalidateQueries({ queryKey: ['appointments'] }) }); const update = useMutation({ mutationFn: ({ id, input }: { id: number; input: Record<string, unknown> }) => agendaApi.appointments.update(id, input), onSuccess: () => client.invalidateQueries({ queryKey: ['appointments'] }) }); const isSaving = create.isPending || update.isPending
  const values = (item: Appointment | null): FormValues => item ? Object.fromEntries(Object.entries(item).filter(([key]) => ['patientId', 'scheduleId', 'healthProfessionalId', 'serviceId', 'branchId', 'consultingRoomId', 'startAt', 'endAt', 'reasonForVisit', 'notes'].includes(key)).map(([key, value]) => [key, String(value ?? '')])) : { patientId: '', scheduleId: '', healthProfessionalId: '', serviceId: '', branchId: '', consultingRoomId: '', startAt: '', endAt: '', reasonForVisit: '', notes: '' }
  const save = async (form: FormValues) => { setFormError(null); try { const input = { ...form, patientId: Number(form.patientId), scheduleId: Number(form.scheduleId), healthProfessionalId: Number(form.healthProfessionalId), serviceId: Number(form.serviceId), branchId: Number(form.branchId), consultingRoomId: form.consultingRoomId ? Number(form.consultingRoomId) : undefined }; if (editing) await update.mutateAsync({ id: editing.appointmentId, input }); else await create.mutateAsync(input); setFormOpen(false); setEditing(null); toast.success(editing ? 'Cita actualizada.' : 'Cita creada.') } catch (error) { setFormError(errorText(error)) } }
  const transition = async (item: Appointment, action: string) => { try { await agendaApi.appointments.transition(item.appointmentId, action); await client.invalidateQueries({ queryKey: ['appointments'] }); toast.success(`Cita: ${actionLabels[action] ?? action}.`) } catch (error) { toast.error(errorText(error)) } }
  if (!can('appointments.read')) return <div className="page-content"><Alert variant="danger" title="Acceso denegado">No tienes permiso para consultar las citas.</Alert></div>
  const columns: DataTableColumn<Appointment>[] = [{ key: 'startAt', header: 'Fecha y hora', cell: (item) => new Date(item.startAt).toLocaleString() }, { key: 'patientId', header: 'Paciente', cell: (item) => item.patientId }, { key: 'serviceId', header: 'Servicio', cell: (item) => item.serviceId }, { key: 'healthProfessionalId', header: 'Profesional', cell: (item) => item.healthProfessionalId }, { key: 'status', header: 'Estado', cell: (item) => <Badge variant={statusVariant(item.status)} dot>{statusLabel(item.status)}</Badge> }, { key: 'actions', header: 'Acciones', align: 'right', cell: (item) => <div className="flex justify-end gap-1">{item.status === 'SCHEDULED' && can('appointments.confirm') && <Button size="sm" variant="ghost" onClick={() => void transition(item, 'confirm')}>Confirmar</Button>}{item.status === 'CONFIRMED' && can('appointments.check-in') && <Button size="sm" variant="ghost" onClick={() => void transition(item, 'check-in')}>Check-in</Button>}{item.status === 'CHECKED_IN' && can('appointments.start') && <Button size="sm" variant="ghost" onClick={() => void transition(item, 'start')}>Iniciar</Button>}{item.status === 'IN_PROGRESS' && can('appointments.complete') && <Button size="sm" variant="ghost" onClick={() => void transition(item, 'complete')}>Completar</Button>}{(item.status === 'SCHEDULED' || item.status === 'CONFIRMED') && can('appointments.no-show') && <Button size="sm" variant="ghost" onClick={() => void transition(item, 'no-show')}>No asistió</Button>}{can('appointments.update') && <Button variant="ghost" size="icon" title="Editar" onClick={() => { setEditing(item); setFormError(null); setFormOpen(true) }}><Edit2 className="h-4 w-4" /></Button>}{can('appointments.cancel') && <Button variant="ghost" size="icon" title="Cancelar" onClick={() => setRemoving(item)}><Trash2 className="h-4 w-4 text-danger" /></Button>}</div> }]
  const pagination = query.data?.pagination
  return <div className="page-content"><PageHeader title="Citas" description="Agenda, consulta y seguimiento de citas por sucursal." actions={can('appointments.create') && <Button leftIcon={<Plus className="h-4 w-4" />} onClick={() => { setEditing(null); setFormError(null); setFormOpen(true) }}>Nueva cita</Button>} /><form onSubmit={(event) => { event.preventDefault(); setFilters(Object.fromEntries(Object.entries(draft).filter(([, value]) => value))); setPage(1) }}><FilterBar><Input value={draft.startDate ?? ''} type="date" onChange={(event) => setDraft({ ...draft, startDate: event.target.value })} leading={<CalendarCheck className="h-4 w-4" />} /><Input value={draft.healthProfessionalId ?? ''} type="number" placeholder="ID profesional" onChange={(event) => setDraft({ ...draft, healthProfessionalId: event.target.value })} /><Select value={draft.status ?? ''} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option value="">Todos los estados</option>{statusOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Button type="submit">Buscar</Button></FilterBar></form>{query.isError && <Alert className="mb-5" variant="danger" title="No se pudieron cargar las citas">{errorText(query.error)}</Alert>}<div className="panel-card overflow-hidden"><DataTable columns={columns} data={query.data?.data ?? []} keyExtractor={(item) => item.appointmentId} loading={query.isLoading} emptyTitle="Sin citas" emptyDescription="No hay citas para los filtros actuales." />{pagination?.type === 'OFFSET' && <Pagination page={pagination.page} pageCount={pagination.totalPages} total={pagination.totalItems} pageSize={pagination.limit} showTotal onChange={setPage} />}</div><Modal open={formOpen} onClose={() => !isSaving && setFormOpen(false)} title={editing ? 'Editar cita' : 'Nueva cita'} size="lg" footer={<><Button variant="outline" onClick={() => setFormOpen(false)}>Cancelar</Button><Button type="submit" form="appointment-form" loading={isSaving}>Guardar</Button></>}><AppointmentForm key={editing?.appointmentId ?? 'new'} values={values(editing)} error={formError} onSubmit={save} /></Modal><ConfirmDialog open={removing !== null} onClose={() => setRemoving(null)} onConfirm={async () => { if (removing) { await transition(removing, 'cancel'); setRemoving(null) } }} title="¿Cancelar cita?" description="La cita se marcará como cancelada." confirmText="Cancelar cita" /></div>
}
