import { useQuery } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { CalendarClock } from 'lucide-react'
import { Alert, Badge, Button, DataTable, Field, Input, PageHeader, type DataTableColumn } from '@/components/ui'
import { agendaApi } from '@/features/agenda/agenda.api'
import type { AvailabilitySlot } from '@/features/agenda/agenda.models'
export default function AvailabilityPage() {
  const [filters, setFilters] = useState({ date: '', healthProfessionalId: '', branchId: '', serviceId: '' }); const [submitted, setSubmitted] = useState<typeof filters | null>(null)
  const query = useQuery({ queryKey: ['availability', submitted], queryFn: () => agendaApi.availability(submitted ?? {}), enabled: submitted !== null })
  const columns: DataTableColumn<AvailabilitySlot>[] = [{ key: 'startAt', header: 'Inicio', cell: (item) => new Date(item.startAt).toLocaleString() }, { key: 'endAt', header: 'Fin', cell: (item) => new Date(item.endAt).toLocaleTimeString() }, { key: 'scheduleId', header: 'Agenda', cell: (item) => item.scheduleId }, { key: 'available', header: 'Disponibilidad', cell: (item) => <Badge variant={item.available ? 'success' : 'danger'} dot>{item.available ? 'Disponible' : 'Ocupado'}</Badge> }]
  return <div className="page-content"><PageHeader title="Disponibilidad" description="Consulta espacios disponibles por fecha, sucursal y profesional." /><form className="panel-card mb-5 flex flex-wrap items-end gap-4 p-5" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(filters) }}><Field label="Fecha" htmlFor="availability-date" required><Input id="availability-date" type="date" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })} required /></Field><Field label="ID profesional" htmlFor="availability-professional"><Input id="availability-professional" type="number" value={filters.healthProfessionalId} onChange={(event) => setFilters({ ...filters, healthProfessionalId: event.target.value })} /></Field><Field label="ID sucursal" htmlFor="availability-branch"><Input id="availability-branch" type="number" value={filters.branchId} onChange={(event) => setFilters({ ...filters, branchId: event.target.value })} /></Field><Field label="ID servicio" htmlFor="availability-service"><Input id="availability-service" type="number" value={filters.serviceId} onChange={(event) => setFilters({ ...filters, serviceId: event.target.value })} /></Field><Button type="submit" leftIcon={<CalendarClock className="h-4 w-4" />}>Consultar</Button></form>{query.isError && <Alert className="mb-5" variant="danger" title="No se pudo consultar disponibilidad">No fue posible obtener los espacios disponibles.</Alert>}<div className="panel-card overflow-hidden"><DataTable columns={columns} data={query.data ?? []} keyExtractor={(item) => `${item.scheduleId}-${item.startAt}`} loading={query.isLoading} emptyTitle="Sin espacios" emptyDescription="Selecciona una fecha y filtros para consultar disponibilidad." /></div></div>
}
