import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1788820234506 implements MigrationInterface {
    name = 'InitMigration1788820234506'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."person_sex_enum" AS ENUM('MALE', 'FEMALE', 'UNSPECIFIED')`);
        await queryRunner.query(`CREATE TABLE "person" ("personId" SERIAL NOT NULL, "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "second_last_name" character varying, "birth_date" date NOT NULL, "sex" "public"."person_sex_enum" NOT NULL, "curp" character varying, "rfc" character varying, "phone" character varying NOT NULL, "secondary_phone" character varying, "email" character varying, "address" character varying, "city" character varying, "state" character varying, "postal_code" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_84a53bea0e639207a7702250a4d" PRIMARY KEY ("personId"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'BLOCKED', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "user" ("userId" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "status" "public"."user_status_enum" NOT NULL, "email_verified_at" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "person_id" integer, CONSTRAINT "PK_d72ea127f30e21753c9e229891e" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TYPE "public"."role_type_enum" AS ENUM('SYSTEM', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."role_status_enum" AS ENUM('ACTIVE', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "role" ("roleId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "type" "public"."role_type_enum" NOT NULL, "status" "public"."role_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_703705ba862c2bb45250962c9e1" PRIMARY KEY ("roleId"))`);
        await queryRunner.query(`CREATE TYPE "public"."permission_status_enum" AS ENUM('ACTIVE', 'DEPRECATED', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "permission" ("permissionId" SERIAL NOT NULL, "code" character varying NOT NULL, "module" character varying NOT NULL, "resource" character varying NOT NULL, "action" character varying NOT NULL, "description" text NOT NULL, "status" "public"."permission_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_86b314be9c1be5c62b3a9d97ae4" PRIMARY KEY ("permissionId"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("rolePermissionId" SERIAL NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "UQ_role_permissions_role_permission" UNIQUE ("role_id", "permission_id"), CONSTRAINT "PK_4f6a0c2c1f39ff29564d33b8662" PRIMARY KEY ("rolePermissionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."branch_status_enum" AS ENUM('ACTIVE', 'TEMPORARILY_CLOSED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "branch" ("branchId" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "email" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "postal_code" character varying NOT NULL, "timezone" character varying NOT NULL, "status" "public"."branch_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fb866244483fa1634abef9f1271" PRIMARY KEY ("branchId"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "user_role" ("userRoleId" SERIAL NOT NULL, "status" "public"."user_role_status_enum" NOT NULL, "valid_from" TIMESTAMP WITH TIME ZONE, "valid_until" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "role_id" integer NOT NULL, "branch_id" integer, CONSTRAINT "PK_84dd97c990a5700a09c2a202b72" PRIMARY KEY ("userRoleId"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_permission_override_effect_enum" AS ENUM('ALLOW', 'DENY')`);
        await queryRunner.query(`CREATE TYPE "public"."user_permission_override_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "user_permission_override" ("userPermissionOverrideId" SERIAL NOT NULL, "effect" "public"."user_permission_override_effect_enum" NOT NULL, "status" "public"."user_permission_override_status_enum" NOT NULL, "reason" text, "valid_from" TIMESTAMP WITH TIME ZONE, "valid_until" TIMESTAMP WITH TIME ZONE, "created_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, "permission_id" integer NOT NULL, "branch_id" integer, CONSTRAINT "PK_4e1ae202d67ec279d394b659ddc" PRIMARY KEY ("userPermissionOverrideId"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("auditLogId" SERIAL NOT NULL, "user_id" integer, "action" character varying NOT NULL, "module" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" integer, "old_values" jsonb, "new_values" jsonb, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_16e719e570e70a2e277569d4d94" PRIMARY KEY ("auditLogId"))`);
        await queryRunner.query(`CREATE TYPE "public"."area_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "area" ("areaId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "status" "public"."area_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branch_id" integer NOT NULL, "parent_area_id" integer, CONSTRAINT "PK_48465cf333cad84a2a3ef535434" PRIMARY KEY ("areaId"))`);
        await queryRunner.query(`CREATE TYPE "public"."consulting_room_status_enum" AS ENUM('AVAILABLE', 'MAINTENANCE', 'TEMPORARILY_UNAVAILABLE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "consulting_room" ("consultingRoomId" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "floor" character varying, "description" text NOT NULL, "status" "public"."consulting_room_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branch_id" integer NOT NULL, "area_id" integer, CONSTRAINT "PK_8b82e4dfd08891946535e8aeb1f" PRIMARY KEY ("consultingRoomId"))`);
        await queryRunner.query(`CREATE TYPE "public"."position_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "position" ("positionId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "status" "public"."position_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_927edd2b828777f0052366195e3" PRIMARY KEY ("positionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."patient_category_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "patient_category" ("patientCategoryId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "status" "public"."patient_category_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5df77aa3c845efe1f4be78b240b" PRIMARY KEY ("patientCategoryId"))`);
        await queryRunner.query(`CREATE TYPE "public"."patient_blood_type_enum" AS ENUM('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."patient_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'DECEASED', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "patient" ("patientId" SERIAL NOT NULL, "patient_number" character varying NOT NULL, "blood_type" "public"."patient_blood_type_enum", "allergies_summary" text, "status" "public"."patient_status_enum" NOT NULL, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "person_id" integer NOT NULL, "patient_category_id" integer NOT NULL, CONSTRAINT "PK_9e4aae494b9d607dd7476c49f03" PRIMARY KEY ("patientId"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_status_enum" AS ENUM('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED')`);
        await queryRunner.query(`CREATE TABLE "employee" ("employeeId" SERIAL NOT NULL, "employee_number" character varying NOT NULL, "hire_date" date NOT NULL, "termination_date" date, "status" "public"."employee_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "person_id" integer NOT NULL, CONSTRAINT "PK_cd21151b14974c7a24e8c24df28" PRIMARY KEY ("employeeId"))`);
        await queryRunner.query(`CREATE TYPE "public"."employee_assignment_assignment_type_enum" AS ENUM('PRIMARY', 'SECONDARY')`);
        await queryRunner.query(`CREATE TYPE "public"."employee_assignment_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'ENDED')`);
        await queryRunner.query(`CREATE TABLE "employee_assignment" ("employeeAssignmentId" SERIAL NOT NULL, "assignment_type" "public"."employee_assignment_assignment_type_enum" NOT NULL, "status" "public"."employee_assignment_status_enum" NOT NULL, "start_date" date NOT NULL, "end_date" date, "employee_id" integer NOT NULL, "branch_id" integer NOT NULL, "area_id" integer, "position_id" integer NOT NULL, CONSTRAINT "PK_fb37047848a1f740ac8992f66b8" PRIMARY KEY ("employeeAssignmentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."health_professional_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "health_professional" ("healthProfessionalId" SERIAL NOT NULL, "professional_license" character varying NOT NULL, "specialty_license" character varying, "bio" text, "status" "public"."health_professional_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "employee_id" integer NOT NULL, CONSTRAINT "PK_fadbee23cbade4efb4a6dff2927" PRIMARY KEY ("healthProfessionalId"))`);
        await queryRunner.query(`CREATE TYPE "public"."specialty_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "specialty" ("specialtyId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "status" "public"."specialty_status_enum" NOT NULL, CONSTRAINT "PK_9e002e236dadadf3d95d4325b69" PRIMARY KEY ("specialtyId"))`);
        await queryRunner.query(`CREATE TYPE "public"."professional_specialties_priority_enum" AS ENUM('PRIMARY', 'SECONDARY')`);
        await queryRunner.query(`CREATE TABLE "professional_specialties" ("professionalSpecialityId" SERIAL NOT NULL, "priority" "public"."professional_specialties_priority_enum" NOT NULL, "health_professional_id" integer NOT NULL, "specialty_id" integer NOT NULL, CONSTRAINT "PK_df151d4b4d4c41ff9b50c72c895" PRIMARY KEY ("professionalSpecialityId"))`);
        await queryRunner.query(`CREATE TYPE "public"."emergency_contact_priority_enum" AS ENUM('PRIMARY', 'SECONDARY')`);
        await queryRunner.query(`CREATE TYPE "public"."emergency_contact_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "emergency_contact" ("emergencyContactId" SERIAL NOT NULL, "name" character varying NOT NULL, "relationship" character varying NOT NULL, "phone" character varying NOT NULL, "secondary_phone" character varying, "email" character varying, "priority" "public"."emergency_contact_priority_enum" NOT NULL, "status" "public"."emergency_contact_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "patient_id" integer NOT NULL, CONSTRAINT "PK_be68f095c057c9687b811e078e4" PRIMARY KEY ("emergencyContactId"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_category_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "service_category" ("serviceCategoryId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "status" "public"."service_category_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "parent_category_id" integer, CONSTRAINT "PK_079d67a26972f35fb59e6072541" PRIMARY KEY ("serviceCategoryId"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_scheduling_type_enum" AS ENUM('APPOINTMENT_REQUIRED', 'WALK_IN_ALLOWED', 'NO_APPOINTMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."service_status_enum" AS ENUM('ACTIVE', 'TEMPORARILY_UNAVAILABLE', 'DISCONTINUED')`);
        await queryRunner.query(`CREATE TABLE "service" ("serviceId" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "duration_minutes" integer NOT NULL, "scheduling_type" "public"."service_scheduling_type_enum" NOT NULL, "status" "public"."service_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "category_id" integer NOT NULL, CONSTRAINT "PK_a33c7dfb23f788d7a9a0b7044da" PRIMARY KEY ("serviceId"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_requirement_requirement_level_enum" AS ENUM('REQUIRED', 'OPTIONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."service_requirement_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "service_requirement" ("serviceRequirementId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "requirement_level" "public"."service_requirement_requirement_level_enum" NOT NULL, "sort_order" integer NOT NULL, "status" "public"."service_requirement_status_enum" NOT NULL, "service_id" integer NOT NULL, CONSTRAINT "PK_0ff84ce0fd8ec017af2d3b8aa17" PRIMARY KEY ("serviceRequirementId"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_assignment_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "service_assignment" ("serviceAssignmentId" SERIAL NOT NULL, "status" "public"."service_assignment_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "service_id" integer NOT NULL, "branch_id" integer NOT NULL, "area_id" integer, "consulting_room_id" integer, "health_professional_id" integer, CONSTRAINT "PK_3e3ef70cd83bf78d8755a54b78f" PRIMARY KEY ("serviceAssignmentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."price_lists_status_enum" AS ENUM('DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "price_lists" ("priceListId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "currency" character varying NOT NULL, "valid_from" date NOT NULL, "valid_until" date, "priority" integer NOT NULL, "status" "public"."price_lists_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "branch_id" integer, "patient_category_id" integer, CONSTRAINT "PK_ca74205bf3643b0aa960703c0f4" PRIMARY KEY ("priceListId"))`);
        await queryRunner.query(`CREATE TYPE "public"."price_list_detail_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "price_list_detail" ("priceListDetailId" SERIAL NOT NULL, "price" numeric(14,2) NOT NULL, "status" "public"."price_list_detail_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "price_list_id" integer NOT NULL, "service_id" integer NOT NULL, CONSTRAINT "UQ_price_list_details_price_list_service" UNIQUE ("price_list_id", "service_id"), CONSTRAINT "PK_32f6c81290edbec804d197a94ce" PRIMARY KEY ("priceListDetailId"))`);
        await queryRunner.query(`CREATE TYPE "public"."patient_special_price_status_enum" AS ENUM('SCHEDULED', 'ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "patient_special_price" ("patientSpecialPriceId" SERIAL NOT NULL, "price" numeric(14,2) NOT NULL, "valid_from" date NOT NULL, "valid_until" date, "reason" text, "status" "public"."patient_special_price_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "patient_id" integer NOT NULL, "service_id" integer NOT NULL, "branch_id" integer, "authorized_by" integer NOT NULL, CONSTRAINT "PK_287cb93d66a533041e01c8cc507" PRIMARY KEY ("patientSpecialPriceId"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "schedule" ("scheduleId" SERIAL NOT NULL, "name" character varying NOT NULL, "slot_duration_minutes" integer NOT NULL, "status" "public"."schedule_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "health_professional_id" integer NOT NULL, "branch_id" integer NOT NULL, "consulting_room_id" integer, CONSTRAINT "PK_c7e04f67bbcc2bd68ec5c996e1f" PRIMARY KEY ("scheduleId"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_hour_day_of_week_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_hour_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "schedule_hour" ("scheduleHourId" SERIAL NOT NULL, "day_of_week" "public"."schedule_hour_day_of_week_enum" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "valid_from" date NOT NULL, "valid_until" date, "status" "public"."schedule_hour_status_enum" NOT NULL, "schedule_id" integer NOT NULL, CONSTRAINT "PK_2394d95d693b99bb8e66cb26318" PRIMARY KEY ("scheduleHourId"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_block_block_type_enum" AS ENUM('VACATION', 'BREAK', 'MEETING', 'MEDICAL_LEAVE', 'PERSONAL', 'MAINTENANCE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_block_status_enum" AS ENUM('ACTIVE', 'CANCELLED', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "schedule_block" ("scheduleBlockId" SERIAL NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "end_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" text NOT NULL, "block_type" "public"."schedule_block_block_type_enum" NOT NULL, "status" "public"."schedule_block_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "schedule_id" integer NOT NULL, "created_by" integer NOT NULL, CONSTRAINT "PK_32fa49370a6b41d73aa1273b3e9" PRIMARY KEY ("scheduleBlockId"))`);
        await queryRunner.query(`CREATE TYPE "public"."appointment_status_enum" AS ENUM('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TABLE "appointment" ("appointmentId" SERIAL NOT NULL, "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "end_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."appointment_status_enum" NOT NULL, "reason_for_visit" text, "notes" text, "price_at_booking" numeric(14,2), "confirmed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "checked_in_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "patient_id" integer NOT NULL, "schedule_id" integer NOT NULL, "health_professional_id" integer NOT NULL, "service_id" integer NOT NULL, "branch_id" integer NOT NULL, "consulting_room_id" integer, "created_by" integer NOT NULL, CONSTRAINT "PK_5daff29f32be6b2c25740d67384" PRIMARY KEY ("appointmentId"))`);
        await queryRunner.query(`CREATE TABLE "appointment_reschedule" ("appointmentRescheduleId" SERIAL NOT NULL, "previous_start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "previous_end_at" TIMESTAMP WITH TIME ZONE NOT NULL, "new_start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "new_end_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reason" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "appointment_id" integer NOT NULL, "changed_by" integer NOT NULL, CONSTRAINT "PK_cfa60c403fe8a2e248bc5afa99c" PRIMARY KEY ("appointmentRescheduleId"))`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_record_status_enum" AS ENUM('OPEN', 'RESTRICTED', 'ARCHIVED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "clinical_record" ("clinicalRecordId" SERIAL NOT NULL, "record_number" character varying NOT NULL, "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."clinical_record_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "patient_id" integer NOT NULL, CONSTRAINT "REL_a6a3b24eaa0e4f8e4820259288" UNIQUE ("patient_id"), CONSTRAINT "PK_2a2b6085ca4ace991ccbe46ad02" PRIMARY KEY ("clinicalRecordId"))`);
        await queryRunner.query(`CREATE TABLE "medical_history" ("medicalHistoryId" SERIAL NOT NULL, "family_history" text, "personal_pathological_history" text, "personal_non_pathological_history" text, "surgical_history" text, "allergies" text, "current_medications" text, "gynecological_history" text, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "clinical_record_id" integer NOT NULL, "updated_by" integer NOT NULL, CONSTRAINT "PK_d2f3a8e5bb3cf09a1fa106b5bdf" PRIMARY KEY ("medicalHistoryId"))`);
        await queryRunner.query(`CREATE TYPE "public"."consultation_status_enum" AS ENUM('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'AMENDED')`);
        await queryRunner.query(`CREATE TABLE "consultation" ("consultationId" SERIAL NOT NULL, "reason" text NOT NULL, "clinical_summary" text, "status" "public"."consultation_status_enum" NOT NULL, "started_at" TIMESTAMP WITH TIME ZONE NOT NULL, "finished_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "clinical_record_id" integer NOT NULL, "appointment_id" integer, "health_professional_id" integer NOT NULL, "branch_id" integer NOT NULL, "consulting_room_id" integer, "service_id" integer, CONSTRAINT "PK_5d85d70b2e449479555af4bf312" PRIMARY KEY ("consultationId"))`);
        await queryRunner.query(`CREATE TYPE "public"."diagnosis_diagnosis_type_enum" AS ENUM('PRESUMPTIVE', 'CONFIRMED', 'DIFFERENTIAL', 'FOLLOW_UP')`);
        await queryRunner.query(`CREATE TYPE "public"."diagnosis_priority_enum" AS ENUM('PRIMARY', 'SECONDARY')`);
        await queryRunner.query(`CREATE TABLE "diagnosis" ("diagnosisId" SERIAL NOT NULL, "code" character varying, "description" text NOT NULL, "diagnosis_type" "public"."diagnosis_diagnosis_type_enum" NOT NULL, "priority" "public"."diagnosis_priority_enum" NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "consultation_id" integer NOT NULL, CONSTRAINT "PK_6f94fe8c72027522b60532d90db" PRIMARY KEY ("diagnosisId"))`);
        await queryRunner.query(`CREATE TYPE "public"."treatment_status_enum" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED', 'SUSPENDED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "treatment" ("treatmentId" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text NOT NULL, "instructions" text NOT NULL, "start_date" date, "end_date" date, "status" "public"."treatment_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "consultation_id" integer NOT NULL, CONSTRAINT "PK_3c21d5d4c8611580bc0b182e992" PRIMARY KEY ("treatmentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."prescription_status_enum" AS ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "prescription" ("prescriptionId" SERIAL NOT NULL, "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" text, "status" "public"."prescription_status_enum" NOT NULL, "consultation_id" integer NOT NULL, "health_professional_id" integer NOT NULL, CONSTRAINT "PK_12ed14cd0536a8bd675d28a5ab8" PRIMARY KEY ("prescriptionId"))`);
        await queryRunner.query(`CREATE TABLE "prescription_item" ("prescriptionItemId" SERIAL NOT NULL, "medication" character varying NOT NULL, "presentation" character varying, "dose" character varying NOT NULL, "route" character varying, "frequency" character varying NOT NULL, "duration" character varying NOT NULL, "instructions" text, "prescription_id" integer NOT NULL, CONSTRAINT "PK_3d1218111614826a51f7fa5257b" PRIMARY KEY ("prescriptionItemId"))`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_note_note_type_enum" AS ENUM('EVOLUTION', 'INITIAL', 'FOLLOW_UP', 'PROCEDURE', 'DISCHARGE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_note_status_enum" AS ENUM('DRAFT', 'SIGNED', 'AMENDED', 'VOIDED')`);
        await queryRunner.query(`CREATE TABLE "clinical_note" ("clinicalNoteId" SERIAL NOT NULL, "note_type" "public"."clinical_note_note_type_enum" NOT NULL, "content" text NOT NULL, "status" "public"."clinical_note_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "consultation_id" integer NOT NULL, "health_professional_id" integer NOT NULL, CONSTRAINT "PK_9cde5f9964281b045137d54b4f2" PRIMARY KEY ("clinicalNoteId"))`);
        await queryRunner.query(`CREATE TYPE "public"."clinical_document_status_enum" AS ENUM('ACTIVE', 'ARCHIVED', 'VOIDED')`);
        await queryRunner.query(`CREATE TABLE "clinical_document" ("clinicalDocumentId" SERIAL NOT NULL, "document_type" character varying NOT NULL, "file_name" character varying NOT NULL, "storage_key" character varying NOT NULL, "mime_type" character varying NOT NULL, "file_size" bigint NOT NULL, "description" text, "status" "public"."clinical_document_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "clinical_record_id" integer NOT NULL, "consultation_id" integer, "uploaded_by" integer NOT NULL, CONSTRAINT "PK_a5943752041300c406f65762326" PRIMARY KEY ("clinicalDocumentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('DRAFT', 'PENDING_PAYMENT', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "order" ("orderId" SERIAL NOT NULL, "folio" character varying NOT NULL, "status" "public"."order_status_enum" NOT NULL, "subtotal" numeric(14,2) NOT NULL, "discount" numeric(14,2) NOT NULL, "tax" numeric(14,2) NOT NULL, "total" numeric(14,2) NOT NULL, "balance" numeric(14,2) NOT NULL, "created_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "patient_id" integer NOT NULL, "appointment_id" integer, "consultation_id" integer, "branch_id" integer NOT NULL, CONSTRAINT "PK_b075313d4d7e1c12f1a6e6359e8" PRIMARY KEY ("orderId"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_detail_status_enum" AS ENUM('PENDING', 'PROVIDED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "order_detail" ("orderDetailId" SERIAL NOT NULL, "description" text NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(14,2) NOT NULL, "discount" numeric(14,2) NOT NULL, "tax" numeric(14,2) NOT NULL, "total" numeric(14,2) NOT NULL, "status" "public"."order_detail_status_enum" NOT NULL, "order_id" integer NOT NULL, "service_id" integer NOT NULL, CONSTRAINT "PK_344d520ab13c07c86096a8a3c72" PRIMARY KEY ("orderDetailId"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("paymentMethodId" SERIAL NOT NULL, "name" character varying NOT NULL, "code" character varying NOT NULL, "status" "public"."payment_method_status_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c07b0b12b34981558fc7612ee8a" PRIMARY KEY ("paymentMethodId"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payment" ("paymentId" SERIAL NOT NULL, "amount" numeric(14,2) NOT NULL, "reference" character varying, "status" "public"."payment_status_enum" NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL, "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "order_id" integer NOT NULL, "payment_method_id" integer NOT NULL, "registered_by" integer NOT NULL, CONSTRAINT "PK_67ee4523b649947b6a7954dc673" PRIMARY KEY ("paymentId"))`);
        await queryRunner.query(`CREATE TYPE "public"."auth_session_status_enum" AS ENUM('ACTIVE', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "auth_session" ("authSessionId" SERIAL NOT NULL, "refresh_token_hash" character varying NOT NULL, "status" "public"."auth_session_status_enum" NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_4564727576782e8ab59628d935e" PRIMARY KEY ("authSessionId"))`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_a4cee7e601d219733b064431fba" FOREIGN KEY ("person_id") REFERENCES "person"("personId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("roleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("permissionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("roleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_8fb261fdaf8d204553f80194d69" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" ADD CONSTRAINT "FK_8d97ae51a17ad07df17a2c8e062" FOREIGN KEY ("user_id") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" ADD CONSTRAINT "FK_da829fa2e592d3202422745ab06" FOREIGN KEY ("permission_id") REFERENCES "permission"("permissionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" ADD CONSTRAINT "FK_62bf116306104502e4734223898" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" ADD CONSTRAINT "FK_c163495d186f4286b8f31b64344" FOREIGN KEY ("created_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7" FOREIGN KEY ("user_id") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area" ADD CONSTRAINT "FK_7681073b1678604c799416e99a1" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "area" ADD CONSTRAINT "FK_ebafd64d6f7c07d856b5820504e" FOREIGN KEY ("parent_area_id") REFERENCES "area"("areaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulting_room" ADD CONSTRAINT "FK_33cac5d0debfe7c7810c7ff3471" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consulting_room" ADD CONSTRAINT "FK_14bb699f012b53b0cf047d0a264" FOREIGN KEY ("area_id") REFERENCES "area"("areaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_b829cf7046dfb9d4e510984e977" FOREIGN KEY ("person_id") REFERENCES "person"("personId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient" ADD CONSTRAINT "FK_a6cfaf50431add795f2c1b4249f" FOREIGN KEY ("patient_category_id") REFERENCES "patient_category"("patientCategoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_84c9ced19362dcb45e274accf8f" FOREIGN KEY ("person_id") REFERENCES "person"("personId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" ADD CONSTRAINT "FK_6184875fe2549189409628424d8" FOREIGN KEY ("employee_id") REFERENCES "employee"("employeeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" ADD CONSTRAINT "FK_40aed63c75833fdf6914520377a" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" ADD CONSTRAINT "FK_055216f229b7c82d74130b1fdbb" FOREIGN KEY ("area_id") REFERENCES "area"("areaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" ADD CONSTRAINT "FK_5f6456a668e9afdce6a00230486" FOREIGN KEY ("position_id") REFERENCES "position"("positionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_professional" ADD CONSTRAINT "FK_081371602e243e0e9a956af484c" FOREIGN KEY ("employee_id") REFERENCES "employee"("employeeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professional_specialties" ADD CONSTRAINT "FK_60adb2b1a7fd0c63ea5bd522b7f" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professional_specialties" ADD CONSTRAINT "FK_7ce1103c67ea34ec7c82115ff56" FOREIGN KEY ("specialty_id") REFERENCES "specialty"("specialtyId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "emergency_contact" ADD CONSTRAINT "FK_24cadee3ed4a2e5c415460f9dc8" FOREIGN KEY ("patient_id") REFERENCES "patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_category" ADD CONSTRAINT "FK_f4915c7a7beb70f473f2987c2a2" FOREIGN KEY ("parent_category_id") REFERENCES "service_category"("serviceCategoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_9d513b39d251063f98f2a7b941d" FOREIGN KEY ("category_id") REFERENCES "service_category"("serviceCategoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requirement" ADD CONSTRAINT "FK_3b991143e589d3695bc9554185d" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignment" ADD CONSTRAINT "FK_fe264bb38bd27e53a7e877b7515" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignment" ADD CONSTRAINT "FK_54b50397dfc1078497ec25d999e" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignment" ADD CONSTRAINT "FK_fa1ebb45bd9c7f758007df051e5" FOREIGN KEY ("area_id") REFERENCES "area"("areaId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignment" ADD CONSTRAINT "FK_865ab6090617b46ef318b664cfd" FOREIGN KEY ("consulting_room_id") REFERENCES "consulting_room"("consultingRoomId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_assignment" ADD CONSTRAINT "FK_c9da4adcbfff8eedde717aaf072" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_lists" ADD CONSTRAINT "FK_db9bc59967605d95279415b7073" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_lists" ADD CONSTRAINT "FK_c95b4fca6019d548b9ed21a9f45" FOREIGN KEY ("patient_category_id") REFERENCES "patient_category"("patientCategoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_detail" ADD CONSTRAINT "FK_2fead8a741bc511fb8def657055" FOREIGN KEY ("price_list_id") REFERENCES "price_lists"("priceListId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_detail" ADD CONSTRAINT "FK_a6392b129e4bee751fbe0072c4e" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" ADD CONSTRAINT "FK_8e663897b47ff87b4a7801c3543" FOREIGN KEY ("patient_id") REFERENCES "patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" ADD CONSTRAINT "FK_4825ed8cbc3572877d8fae1fd8d" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" ADD CONSTRAINT "FK_2b0323a93d36cae51f88cbc0ccd" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" ADD CONSTRAINT "FK_90068626ff6179d12452798a730" FOREIGN KEY ("authorized_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_9e7fb2b023a429ccd1ce5fbde5d" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_8d98f648451dc8e4dda48693d2a" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule" ADD CONSTRAINT "FK_0fd28e580ff15f54f2925507462" FOREIGN KEY ("consulting_room_id") REFERENCES "consulting_room"("consultingRoomId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_hour" ADD CONSTRAINT "FK_df8ecaf65250d53d0a92c678147" FOREIGN KEY ("schedule_id") REFERENCES "schedule"("scheduleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_block" ADD CONSTRAINT "FK_b7d723185230b69ac6882c7892d" FOREIGN KEY ("schedule_id") REFERENCES "schedule"("scheduleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_block" ADD CONSTRAINT "FK_4fcf8d1f5a8b0ce311b689cb32a" FOREIGN KEY ("created_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_86b3e35a97e289071b4785a1402" FOREIGN KEY ("patient_id") REFERENCES "patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_1dd29956529ee1c9cf4a055312f" FOREIGN KEY ("schedule_id") REFERENCES "schedule"("scheduleId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_02f2fa365f409c8f41a1a26f4c2" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_a170b01d5845a629233fb80a51a" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_7cd74ebb05fd8cd8e93ad958ede" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_d04d18a32d74427fa6674b79af5" FOREIGN KEY ("consulting_room_id") REFERENCES "consulting_room"("consultingRoomId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment" ADD CONSTRAINT "FK_97a555b1fd188ab0f8895a0e6e1" FOREIGN KEY ("created_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_reschedule" ADD CONSTRAINT "FK_4a3a36172997476400028b3a4a1" FOREIGN KEY ("appointment_id") REFERENCES "appointment"("appointmentId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_reschedule" ADD CONSTRAINT "FK_874645bfb90e244c0fc256e2259" FOREIGN KEY ("changed_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_record" ADD CONSTRAINT "FK_a6a3b24eaa0e4f8e4820259288f" FOREIGN KEY ("patient_id") REFERENCES "patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_history" ADD CONSTRAINT "FK_8b0aa0196fa0ac2554dc5064c6d" FOREIGN KEY ("clinical_record_id") REFERENCES "clinical_record"("clinicalRecordId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_history" ADD CONSTRAINT "FK_d67cae7455fc87f97e7f5a0cd0a" FOREIGN KEY ("updated_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_614d3fbe866f447c41233dad22b" FOREIGN KEY ("clinical_record_id") REFERENCES "clinical_record"("clinicalRecordId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_0aa1d27dba50dc2b9781bf2252e" FOREIGN KEY ("appointment_id") REFERENCES "appointment"("appointmentId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_a645bd881588a1b77a1bb7a7545" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_e50136bb526df6b65cdc0ef011a" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_661f5b848edb79d7121042415b1" FOREIGN KEY ("consulting_room_id") REFERENCES "consulting_room"("consultingRoomId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_b40d8f8931d0d3af036abb81d54" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "diagnosis" ADD CONSTRAINT "FK_0e17ea9382d53e9cdada55e0e9e" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "treatment" ADD CONSTRAINT "FK_3dad9417528be8ec3892cc6217e" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription" ADD CONSTRAINT "FK_f7abc997a5be26daf4b627331f3" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription" ADD CONSTRAINT "FK_8763e2b181fa9fa89b38705d8cd" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_item" ADD CONSTRAINT "FK_dc8e212287b4eca96f5453e3045" FOREIGN KEY ("prescription_id") REFERENCES "prescription"("prescriptionId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_note" ADD CONSTRAINT "FK_309919cf56c953e945834843fd8" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_note" ADD CONSTRAINT "FK_7d2c59087f268b9f6d1c473c3af" FOREIGN KEY ("health_professional_id") REFERENCES "health_professional"("healthProfessionalId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_document" ADD CONSTRAINT "FK_c3ceadc54be43ce19c2441903cb" FOREIGN KEY ("clinical_record_id") REFERENCES "clinical_record"("clinicalRecordId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_document" ADD CONSTRAINT "FK_6672383e27cd9e4698b042dfaeb" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clinical_document" ADD CONSTRAINT "FK_c6b8773b0b31fbbcd54cfd3a7ae" FOREIGN KEY ("uploaded_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_362804ba457f1a4d95370a49970" FOREIGN KEY ("patient_id") REFERENCES "patient"("patientId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_e18a973d8b511399f837687b43c" FOREIGN KEY ("appointment_id") REFERENCES "appointment"("appointmentId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_f6edd4ed100b5fc0b4962a04ba5" FOREIGN KEY ("consultation_id") REFERENCES "consultation"("consultationId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_bffc1bebf6db72c49d80df64b24" FOREIGN KEY ("branch_id") REFERENCES "branch"("branchId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_ed947f1c5c1282f6fd4405ffd87" FOREIGN KEY ("created_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be" FOREIGN KEY ("order_id") REFERENCES "order"("orderId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_detail" ADD CONSTRAINT "FK_815ae0ed6a604ff7d531a44d6f1" FOREIGN KEY ("service_id") REFERENCES "service"("serviceId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f5221735ace059250daac9d9803" FOREIGN KEY ("order_id") REFERENCES "order"("orderId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_365af7f69f9142427cf30395b00" FOREIGN KEY ("payment_method_id") REFERENCES "payment_method"("paymentMethodId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_feb5353357b651e4c8d8576684f" FOREIGN KEY ("registered_by") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_session" ADD CONSTRAINT "FK_b8783d517fab10672700a39cb49" FOREIGN KEY ("user_id") REFERENCES "user"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth_session" DROP CONSTRAINT "FK_b8783d517fab10672700a39cb49"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_feb5353357b651e4c8d8576684f"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_365af7f69f9142427cf30395b00"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f5221735ace059250daac9d9803"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_815ae0ed6a604ff7d531a44d6f1"`);
        await queryRunner.query(`ALTER TABLE "order_detail" DROP CONSTRAINT "FK_a6ac5c99b8c02bd4ee53d3785be"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_ed947f1c5c1282f6fd4405ffd87"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_bffc1bebf6db72c49d80df64b24"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_f6edd4ed100b5fc0b4962a04ba5"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_e18a973d8b511399f837687b43c"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_362804ba457f1a4d95370a49970"`);
        await queryRunner.query(`ALTER TABLE "clinical_document" DROP CONSTRAINT "FK_c6b8773b0b31fbbcd54cfd3a7ae"`);
        await queryRunner.query(`ALTER TABLE "clinical_document" DROP CONSTRAINT "FK_6672383e27cd9e4698b042dfaeb"`);
        await queryRunner.query(`ALTER TABLE "clinical_document" DROP CONSTRAINT "FK_c3ceadc54be43ce19c2441903cb"`);
        await queryRunner.query(`ALTER TABLE "clinical_note" DROP CONSTRAINT "FK_7d2c59087f268b9f6d1c473c3af"`);
        await queryRunner.query(`ALTER TABLE "clinical_note" DROP CONSTRAINT "FK_309919cf56c953e945834843fd8"`);
        await queryRunner.query(`ALTER TABLE "prescription_item" DROP CONSTRAINT "FK_dc8e212287b4eca96f5453e3045"`);
        await queryRunner.query(`ALTER TABLE "prescription" DROP CONSTRAINT "FK_8763e2b181fa9fa89b38705d8cd"`);
        await queryRunner.query(`ALTER TABLE "prescription" DROP CONSTRAINT "FK_f7abc997a5be26daf4b627331f3"`);
        await queryRunner.query(`ALTER TABLE "treatment" DROP CONSTRAINT "FK_3dad9417528be8ec3892cc6217e"`);
        await queryRunner.query(`ALTER TABLE "diagnosis" DROP CONSTRAINT "FK_0e17ea9382d53e9cdada55e0e9e"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_b40d8f8931d0d3af036abb81d54"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_661f5b848edb79d7121042415b1"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_e50136bb526df6b65cdc0ef011a"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_a645bd881588a1b77a1bb7a7545"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_0aa1d27dba50dc2b9781bf2252e"`);
        await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_614d3fbe866f447c41233dad22b"`);
        await queryRunner.query(`ALTER TABLE "medical_history" DROP CONSTRAINT "FK_d67cae7455fc87f97e7f5a0cd0a"`);
        await queryRunner.query(`ALTER TABLE "medical_history" DROP CONSTRAINT "FK_8b0aa0196fa0ac2554dc5064c6d"`);
        await queryRunner.query(`ALTER TABLE "clinical_record" DROP CONSTRAINT "FK_a6a3b24eaa0e4f8e4820259288f"`);
        await queryRunner.query(`ALTER TABLE "appointment_reschedule" DROP CONSTRAINT "FK_874645bfb90e244c0fc256e2259"`);
        await queryRunner.query(`ALTER TABLE "appointment_reschedule" DROP CONSTRAINT "FK_4a3a36172997476400028b3a4a1"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_97a555b1fd188ab0f8895a0e6e1"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_d04d18a32d74427fa6674b79af5"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_7cd74ebb05fd8cd8e93ad958ede"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_a170b01d5845a629233fb80a51a"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_02f2fa365f409c8f41a1a26f4c2"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_1dd29956529ee1c9cf4a055312f"`);
        await queryRunner.query(`ALTER TABLE "appointment" DROP CONSTRAINT "FK_86b3e35a97e289071b4785a1402"`);
        await queryRunner.query(`ALTER TABLE "schedule_block" DROP CONSTRAINT "FK_4fcf8d1f5a8b0ce311b689cb32a"`);
        await queryRunner.query(`ALTER TABLE "schedule_block" DROP CONSTRAINT "FK_b7d723185230b69ac6882c7892d"`);
        await queryRunner.query(`ALTER TABLE "schedule_hour" DROP CONSTRAINT "FK_df8ecaf65250d53d0a92c678147"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_0fd28e580ff15f54f2925507462"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_8d98f648451dc8e4dda48693d2a"`);
        await queryRunner.query(`ALTER TABLE "schedule" DROP CONSTRAINT "FK_9e7fb2b023a429ccd1ce5fbde5d"`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" DROP CONSTRAINT "FK_90068626ff6179d12452798a730"`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" DROP CONSTRAINT "FK_2b0323a93d36cae51f88cbc0ccd"`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" DROP CONSTRAINT "FK_4825ed8cbc3572877d8fae1fd8d"`);
        await queryRunner.query(`ALTER TABLE "patient_special_price" DROP CONSTRAINT "FK_8e663897b47ff87b4a7801c3543"`);
        await queryRunner.query(`ALTER TABLE "price_list_detail" DROP CONSTRAINT "FK_a6392b129e4bee751fbe0072c4e"`);
        await queryRunner.query(`ALTER TABLE "price_list_detail" DROP CONSTRAINT "FK_2fead8a741bc511fb8def657055"`);
        await queryRunner.query(`ALTER TABLE "price_lists" DROP CONSTRAINT "FK_c95b4fca6019d548b9ed21a9f45"`);
        await queryRunner.query(`ALTER TABLE "price_lists" DROP CONSTRAINT "FK_db9bc59967605d95279415b7073"`);
        await queryRunner.query(`ALTER TABLE "service_assignment" DROP CONSTRAINT "FK_c9da4adcbfff8eedde717aaf072"`);
        await queryRunner.query(`ALTER TABLE "service_assignment" DROP CONSTRAINT "FK_865ab6090617b46ef318b664cfd"`);
        await queryRunner.query(`ALTER TABLE "service_assignment" DROP CONSTRAINT "FK_fa1ebb45bd9c7f758007df051e5"`);
        await queryRunner.query(`ALTER TABLE "service_assignment" DROP CONSTRAINT "FK_54b50397dfc1078497ec25d999e"`);
        await queryRunner.query(`ALTER TABLE "service_assignment" DROP CONSTRAINT "FK_fe264bb38bd27e53a7e877b7515"`);
        await queryRunner.query(`ALTER TABLE "service_requirement" DROP CONSTRAINT "FK_3b991143e589d3695bc9554185d"`);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_9d513b39d251063f98f2a7b941d"`);
        await queryRunner.query(`ALTER TABLE "service_category" DROP CONSTRAINT "FK_f4915c7a7beb70f473f2987c2a2"`);
        await queryRunner.query(`ALTER TABLE "emergency_contact" DROP CONSTRAINT "FK_24cadee3ed4a2e5c415460f9dc8"`);
        await queryRunner.query(`ALTER TABLE "professional_specialties" DROP CONSTRAINT "FK_7ce1103c67ea34ec7c82115ff56"`);
        await queryRunner.query(`ALTER TABLE "professional_specialties" DROP CONSTRAINT "FK_60adb2b1a7fd0c63ea5bd522b7f"`);
        await queryRunner.query(`ALTER TABLE "health_professional" DROP CONSTRAINT "FK_081371602e243e0e9a956af484c"`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" DROP CONSTRAINT "FK_5f6456a668e9afdce6a00230486"`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" DROP CONSTRAINT "FK_055216f229b7c82d74130b1fdbb"`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" DROP CONSTRAINT "FK_40aed63c75833fdf6914520377a"`);
        await queryRunner.query(`ALTER TABLE "employee_assignment" DROP CONSTRAINT "FK_6184875fe2549189409628424d8"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_84c9ced19362dcb45e274accf8f"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_a6cfaf50431add795f2c1b4249f"`);
        await queryRunner.query(`ALTER TABLE "patient" DROP CONSTRAINT "FK_b829cf7046dfb9d4e510984e977"`);
        await queryRunner.query(`ALTER TABLE "consulting_room" DROP CONSTRAINT "FK_14bb699f012b53b0cf047d0a264"`);
        await queryRunner.query(`ALTER TABLE "consulting_room" DROP CONSTRAINT "FK_33cac5d0debfe7c7810c7ff3471"`);
        await queryRunner.query(`ALTER TABLE "area" DROP CONSTRAINT "FK_ebafd64d6f7c07d856b5820504e"`);
        await queryRunner.query(`ALTER TABLE "area" DROP CONSTRAINT "FK_7681073b1678604c799416e99a1"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7"`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" DROP CONSTRAINT "FK_c163495d186f4286b8f31b64344"`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" DROP CONSTRAINT "FK_62bf116306104502e4734223898"`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" DROP CONSTRAINT "FK_da829fa2e592d3202422745ab06"`);
        await queryRunner.query(`ALTER TABLE "user_permission_override" DROP CONSTRAINT "FK_8d97ae51a17ad07df17a2c8e062"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_8fb261fdaf8d204553f80194d69"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_a4cee7e601d219733b064431fba"`);
        await queryRunner.query(`DROP TABLE "auth_session"`);
        await queryRunner.query(`DROP TYPE "public"."auth_session_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_detail"`);
        await queryRunner.query(`DROP TYPE "public"."order_detail_status_enum"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "clinical_document"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_document_status_enum"`);
        await queryRunner.query(`DROP TABLE "clinical_note"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_note_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_note_note_type_enum"`);
        await queryRunner.query(`DROP TABLE "prescription_item"`);
        await queryRunner.query(`DROP TABLE "prescription"`);
        await queryRunner.query(`DROP TYPE "public"."prescription_status_enum"`);
        await queryRunner.query(`DROP TABLE "treatment"`);
        await queryRunner.query(`DROP TYPE "public"."treatment_status_enum"`);
        await queryRunner.query(`DROP TABLE "diagnosis"`);
        await queryRunner.query(`DROP TYPE "public"."diagnosis_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."diagnosis_diagnosis_type_enum"`);
        await queryRunner.query(`DROP TABLE "consultation"`);
        await queryRunner.query(`DROP TYPE "public"."consultation_status_enum"`);
        await queryRunner.query(`DROP TABLE "medical_history"`);
        await queryRunner.query(`DROP TABLE "clinical_record"`);
        await queryRunner.query(`DROP TYPE "public"."clinical_record_status_enum"`);
        await queryRunner.query(`DROP TABLE "appointment_reschedule"`);
        await queryRunner.query(`DROP TABLE "appointment"`);
        await queryRunner.query(`DROP TYPE "public"."appointment_status_enum"`);
        await queryRunner.query(`DROP TABLE "schedule_block"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_block_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_block_block_type_enum"`);
        await queryRunner.query(`DROP TABLE "schedule_hour"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_hour_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_hour_day_of_week_enum"`);
        await queryRunner.query(`DROP TABLE "schedule"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_status_enum"`);
        await queryRunner.query(`DROP TABLE "patient_special_price"`);
        await queryRunner.query(`DROP TYPE "public"."patient_special_price_status_enum"`);
        await queryRunner.query(`DROP TABLE "price_list_detail"`);
        await queryRunner.query(`DROP TYPE "public"."price_list_detail_status_enum"`);
        await queryRunner.query(`DROP TABLE "price_lists"`);
        await queryRunner.query(`DROP TYPE "public"."price_lists_status_enum"`);
        await queryRunner.query(`DROP TABLE "service_assignment"`);
        await queryRunner.query(`DROP TYPE "public"."service_assignment_status_enum"`);
        await queryRunner.query(`DROP TABLE "service_requirement"`);
        await queryRunner.query(`DROP TYPE "public"."service_requirement_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."service_requirement_requirement_level_enum"`);
        await queryRunner.query(`DROP TABLE "service"`);
        await queryRunner.query(`DROP TYPE "public"."service_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."service_scheduling_type_enum"`);
        await queryRunner.query(`DROP TABLE "service_category"`);
        await queryRunner.query(`DROP TYPE "public"."service_category_status_enum"`);
        await queryRunner.query(`DROP TABLE "emergency_contact"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_contact_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."emergency_contact_priority_enum"`);
        await queryRunner.query(`DROP TABLE "professional_specialties"`);
        await queryRunner.query(`DROP TYPE "public"."professional_specialties_priority_enum"`);
        await queryRunner.query(`DROP TABLE "specialty"`);
        await queryRunner.query(`DROP TYPE "public"."specialty_status_enum"`);
        await queryRunner.query(`DROP TABLE "health_professional"`);
        await queryRunner.query(`DROP TYPE "public"."health_professional_status_enum"`);
        await queryRunner.query(`DROP TABLE "employee_assignment"`);
        await queryRunner.query(`DROP TYPE "public"."employee_assignment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."employee_assignment_assignment_type_enum"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP TYPE "public"."employee_status_enum"`);
        await queryRunner.query(`DROP TABLE "patient"`);
        await queryRunner.query(`DROP TYPE "public"."patient_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."patient_blood_type_enum"`);
        await queryRunner.query(`DROP TABLE "patient_category"`);
        await queryRunner.query(`DROP TYPE "public"."patient_category_status_enum"`);
        await queryRunner.query(`DROP TABLE "position"`);
        await queryRunner.query(`DROP TYPE "public"."position_status_enum"`);
        await queryRunner.query(`DROP TABLE "consulting_room"`);
        await queryRunner.query(`DROP TYPE "public"."consulting_room_status_enum"`);
        await queryRunner.query(`DROP TABLE "area"`);
        await queryRunner.query(`DROP TYPE "public"."area_status_enum"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "user_permission_override"`);
        await queryRunner.query(`DROP TYPE "public"."user_permission_override_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_permission_override_effect_enum"`);
        await queryRunner.query(`DROP TABLE "user_role"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_status_enum"`);
        await queryRunner.query(`DROP TABLE "branch"`);
        await queryRunner.query(`DROP TYPE "public"."branch_status_enum"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TYPE "public"."permission_status_enum"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TYPE "public"."role_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."role_type_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`DROP TYPE "public"."person_sex_enum"`);
    }

}
