export enum ScheduleBlockType {
  VACATION = 'VACATION',
  BREAK = 'BREAK',
  MEETING = 'MEETING',
  MEDICAL_LEAVE = 'MEDICAL_LEAVE',
  PERSONAL = 'PERSONAL',
  MAINTENANCE = 'MAINTENANCE',
  OTHER = 'OTHER',
}
