import { PermissionAction } from '../enum/permission-action.enum';
import { PermissionResource } from '../enum/permission-resource.enum';

/** Valid permission actions by domain resource. Keep this explicit to prevent meaningless combinations. */
export const PERMISSION_CATALOG: Record<PermissionResource, readonly PermissionAction[]> = {
  [PermissionResource.USERS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.CHANGE_PASSWORD,
    PermissionAction.MANAGE_ROLES,
    PermissionAction.MANAGE_OVERRIDES,
  ],
  [PermissionResource.ROLES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.MANAGE_PERMISSIONS,
  ],
  [PermissionResource.PERMISSIONS]: [PermissionAction.READ],
  [PermissionResource.PEOPLE]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
  ],
  [PermissionResource.PATIENTS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.EXPORT,
  ],
  [PermissionResource.CLINICAL_RECORDS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.RESTRICT,
    PermissionAction.UNRESTRICT,
    PermissionAction.CLOSE,
    PermissionAction.REOPEN,
    PermissionAction.UPLOAD,
    PermissionAction.DOWNLOAD,
  ],
  [PermissionResource.CONSULTATIONS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.START,
    PermissionAction.COMPLETE,
    PermissionAction.CANCEL,
    PermissionAction.AMEND,
  ],
  [PermissionResource.PRESCRIPTIONS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.COMPLETE,
    PermissionAction.CANCEL,
    PermissionAction.VOID,
  ],
  [PermissionResource.APPOINTMENTS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.CONFIRM,
    PermissionAction.CHECK_IN,
    PermissionAction.START,
    PermissionAction.COMPLETE,
    PermissionAction.CANCEL,
    PermissionAction.RESCHEDULE,
    PermissionAction.MARK_NO_SHOW,
  ],
  [PermissionResource.SCHEDULES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.BLOCK,
    PermissionAction.UNBLOCK,
  ],
  [PermissionResource.ORDERS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.CANCEL,
    PermissionAction.REFUND,
    PermissionAction.EXPORT,
  ],
  [PermissionResource.PAYMENTS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.CONFIRM,
    PermissionAction.CANCEL,
    PermissionAction.VOID,
    PermissionAction.REFUND,
    PermissionAction.EXPORT,
  ],
  [PermissionResource.PRICE_LISTS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.PUBLISH,
    PermissionAction.UNPUBLISH,
    PermissionAction.APPROVE,
  ],
  [PermissionResource.PATIENT_SPECIAL_PRICES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.APPROVE,
  ],
  [PermissionResource.SERVICES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.ASSIGN,
    PermissionAction.UNASSIGN,
  ],
  [PermissionResource.SERVICE_CATEGORIES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.BRANCHES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.CONSULTING_ROOMS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.EMPLOYEES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.ASSIGN,
    PermissionAction.UNASSIGN,
  ],
  [PermissionResource.HEALTH_PROFESSIONALS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
    PermissionAction.ASSIGN,
    PermissionAction.UNASSIGN,
  ],
  [PermissionResource.SPECIALTIES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.POSITIONS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.AREAS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.PATIENT_CATEGORIES]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.PAYMENT_METHODS]: [
    PermissionAction.CREATE,
    PermissionAction.READ,
    PermissionAction.UPDATE,
    PermissionAction.DELETE,
    PermissionAction.ARCHIVE,
    PermissionAction.ACTIVATE,
    PermissionAction.DEACTIVATE,
  ],
  [PermissionResource.AUDIT_LOGS]: [
    PermissionAction.READ,
    PermissionAction.EXPORT
  ],
  [PermissionResource.SESSIONS]: [
    PermissionAction.READ,
    PermissionAction.REVOKE_SESSION
  ],
};
