import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Plus, Trash2 } from 'lucide-react'
import { useBranch } from '@/app/providers/branch-context'
import { Alert, Badge, Button, DataTable, Field, Input, PageHeader, Select, toast, type DataTableColumn } from '@/components/ui'
import { ApiError } from '@/infrastructure/http'
import { employeesApi, healthProfessionalsApi, servicesApi } from '@/features/staff/staff.api'
import type { EmployeeAssignment, ProfessionalSpecialty, ServiceAssignment, ServiceRequirement } from '@/features/staff/staff.models'

const errorText = (error: unknown) => error instanceof ApiError ? error.messages.join(' ') : error instanceof Error ? error.message : 'No fue posible completar la operación.'
const value = (form: HTMLFormElement, name: string) => new FormData(form).get(name)?.toString() ?? ''
const numberValue = (form: HTMLFormElement, name: string) => Number(value(form, name))

function RelationLayout({ title, description, backPath, children }: { title: string; description: string; backPath: string; children: ReactNode }) {
  return <div className="page-content"><PageHeader title={title} description={description} actions={<Link className="inline-flex h-9 items-center gap-2 rounded-lg border border-line bg-surface px-4 text-sm font-medium text-ink hover:border-primary hover:text-primary" to={backPath}><ArrowLeft className="h-4 w-4" />Volver</Link>} />{children}</div>
}

export function EmployeeAssignmentsPage() {
  const id = Number(useParams().id)
  const { can } = useBranch()
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['employee-assignments', id], queryFn: () => employeesApi.assignments(id), enabled: can('employees.read') && id > 0 })
  const mutation = useMutation({ mutationFn: (form: HTMLFormElement) => employeesApi.assign(id, { branchId: numberValue(form, 'branchId'), areaId: value(form, 'areaId'), positionId: numberValue(form, 'positionId'), assignmentType: value(form, 'assignmentType'), startDate: value(form, 'startDate') }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['employee-assignments', id] }); toast.success('Asignación creada.') } })
  const end = useMutation({ mutationFn: ({ employeeAssignmentId }: EmployeeAssignment) => employeesApi.endAssignment(id, employeeAssignmentId, {}), onSuccess: () => { void client.invalidateQueries({ queryKey: ['employee-assignments', id] }); toast.success('Asignación finalizada.') } })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); mutation.mutate(event.currentTarget) }
  const columns: DataTableColumn<EmployeeAssignment>[] = [
    { key: 'branchId', header: 'Sucursal', cell: (item) => item.branchId }, { key: 'areaId', header: 'Área', cell: (item) => item.areaId ?? '-' }, { key: 'positionId', header: 'Puesto', cell: (item) => item.positionId }, { key: 'assignmentType', header: 'Tipo', cell: (item) => item.assignmentType }, { key: 'status', header: 'Estado', cell: (item) => <Badge variant={item.status === 'ACTIVE' ? 'success' : 'neutral'}>{item.status}</Badge> }, { key: 'actions', header: '', align: 'right', cell: (item) => item.status === 'ACTIVE' && <Button variant="ghost" size="icon" title="Finalizar" onClick={() => end.mutate(item)}><Trash2 className="h-4 w-4 text-danger" /></Button> },
  ]
  return <RelationLayout title="Asignaciones del empleado" description="Administra sucursal, área y puesto del empleado." backPath="/dashboard/employees"><div className="panel-card mb-5 p-5"><form className="grid gap-4 sm:grid-cols-5" onSubmit={submit}><Field label="Sucursal" htmlFor="branchId" required><Input id="branchId" name="branchId" type="number" required /></Field><Field label="Área" htmlFor="areaId"><Input id="areaId" name="areaId" type="number" /></Field><Field label="Puesto" htmlFor="positionId" required><Input id="positionId" name="positionId" type="number" required /></Field><Field label="Tipo" htmlFor="assignmentType" required><Select id="assignmentType" name="assignmentType" defaultValue="PRIMARY"><option value="PRIMARY">Principal</option><option value="SECONDARY">Secundaria</option><option value="TEMPORARY">Temporal</option></Select></Field><Field label="Inicio" htmlFor="startDate" required><Input id="startDate" name="startDate" type="date" required /></Field><Button type="submit" loading={mutation.isPending} leftIcon={<Plus className="h-4 w-4" />}>Asignar</Button></form>{mutation.isError && <Alert className="mt-4" variant="danger" title="No se pudo asignar">{errorText(mutation.error)}</Alert>}</div><div className="panel-card overflow-hidden"><DataTable columns={columns} data={query.data ?? []} keyExtractor={(item) => item.employeeAssignmentId} loading={query.isLoading} emptyTitle="Sin asignaciones" emptyDescription="Este empleado aún no tiene asignaciones." /></div></RelationLayout>
}

export function ProfessionalSpecialtiesPage() {
  const id = Number(useParams().id); const { can } = useBranch(); const client = useQueryClient()
  const query = useQuery({ queryKey: ['professional-specialties', id], queryFn: () => healthProfessionalsApi.specialties(id), enabled: can('health-professionals.read') && id > 0 })
  const mutation = useMutation({ mutationFn: (form: HTMLFormElement) => healthProfessionalsApi.assignSpecialty(id, { specialtyId: numberValue(form, 'specialtyId'), priority: value(form, 'priority') }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['professional-specialties', id] }); toast.success('Especialidad asignada.') } })
  const remove = useMutation({ mutationFn: (item: ProfessionalSpecialty) => healthProfessionalsApi.removeSpecialty(id, item.professionalSpecialtyId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['professional-specialties', id] }); toast.success('Especialidad retirada.') } })
  const columns: DataTableColumn<ProfessionalSpecialty>[] = [{ key: 'specialtyId', header: 'Especialidad', cell: (item) => item.specialtyId }, { key: 'priority', header: 'Prioridad', cell: (item) => item.priority }, { key: 'actions', header: '', align: 'right', cell: (item) => <Button variant="ghost" size="icon" title="Retirar" onClick={() => remove.mutate(item)}><Trash2 className="h-4 w-4 text-danger" /></Button> }]
  return <RelationLayout title="Especialidades del profesional" description="Relaciona las especialidades habilitadas para este profesional." backPath="/dashboard/health-professionals"><div className="panel-card mb-5 p-5"><form className="flex flex-wrap items-end gap-4" onSubmit={(event) => { event.preventDefault(); mutation.mutate(event.currentTarget) }}><Field label="ID de especialidad" htmlFor="specialtyId" required><Input id="specialtyId" name="specialtyId" type="number" required /></Field><Field label="Prioridad" htmlFor="priority" required><Select id="priority" name="priority" defaultValue="PRIMARY"><option value="PRIMARY">Principal</option><option value="SECONDARY">Secundaria</option></Select></Field><Button type="submit" loading={mutation.isPending} leftIcon={<Plus className="h-4 w-4" />}>Asignar</Button></form></div><div className="panel-card overflow-hidden"><DataTable columns={columns} data={query.data ?? []} keyExtractor={(item) => item.professionalSpecialtyId} loading={query.isLoading} emptyTitle="Sin especialidades" emptyDescription="Este profesional aún no tiene especialidades." /></div></RelationLayout>
}

export function ServiceRelationshipsPage() {
  const id = Number(useParams().id); const client = useQueryClient(); const [tab, setTab] = useState<'requirements' | 'assignments'>('requirements')
  const requirements = useQuery({ queryKey: ['service-requirements', id], queryFn: () => servicesApi.requirements(id), enabled: id > 0 && tab === 'requirements' })
  const assignments = useQuery({ queryKey: ['service-assignments', id], queryFn: () => servicesApi.assignments(id), enabled: id > 0 && tab === 'assignments' })
  const addRequirement = useMutation({ mutationFn: (form: HTMLFormElement) => servicesApi.createRequirement(id, { name: value(form, 'name'), description: value(form, 'description'), requirementLevel: value(form, 'requirementLevel'), sortOrder: numberValue(form, 'sortOrder') }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['service-requirements', id] }); toast.success('Requisito creado.') } })
  const addAssignment = useMutation({ mutationFn: (form: HTMLFormElement) => servicesApi.assign(id, { branchId: numberValue(form, 'branchId'), areaId: value(form, 'areaId'), consultingRoomId: value(form, 'consultingRoomId'), healthProfessionalId: value(form, 'healthProfessionalId') }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['service-assignments', id] }); toast.success('Servicio asignado.') } })
  const remove = useMutation({ mutationFn: (item: ServiceAssignment) => servicesApi.removeAssignment(id, item.serviceAssignmentId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['service-assignments', id] }); toast.success('Asignación retirada.') } })
  const requirementColumns: DataTableColumn<ServiceRequirement>[] = [{ key: 'name', header: 'Nombre', cell: (item) => item.name }, { key: 'requirementLevel', header: 'Nivel', cell: (item) => item.requirementLevel }, { key: 'sortOrder', header: 'Orden', cell: (item) => item.sortOrder }]
  const assignmentColumns: DataTableColumn<ServiceAssignment>[] = [{ key: 'branchId', header: 'Sucursal', cell: (item) => item.branchId }, { key: 'areaId', header: 'Área', cell: (item) => item.areaId ?? '-' }, { key: 'consultingRoomId', header: 'Consultorio', cell: (item) => item.consultingRoomId ?? '-' }, { key: 'healthProfessionalId', header: 'Profesional', cell: (item) => item.healthProfessionalId ?? '-' }, { key: 'actions', header: '', align: 'right', cell: (item) => <Button variant="ghost" size="icon" onClick={() => remove.mutate(item)} title="Retirar"><Trash2 className="h-4 w-4 text-danger" /></Button> }]
  return <RelationLayout title="Configuración del servicio" description="Administra requisitos y asignaciones operativas del servicio." backPath="/dashboard/services"><div className="mb-5 flex gap-2"><Button variant={tab === 'requirements' ? 'primary' : 'outline'} onClick={() => setTab('requirements')}>Requisitos</Button><Button variant={tab === 'assignments' ? 'primary' : 'outline'} onClick={() => setTab('assignments')}>Asignaciones</Button></div>{tab === 'requirements' ? <><div className="panel-card mb-5 p-5"><form className="grid gap-4 sm:grid-cols-4" onSubmit={(event) => { event.preventDefault(); addRequirement.mutate(event.currentTarget) }}><Field label="Nombre" htmlFor="name" required><Input id="name" name="name" required /></Field><Field label="Descripción" htmlFor="description" required><Input id="description" name="description" required /></Field><Field label="Nivel" htmlFor="requirementLevel" required><Select id="requirementLevel" name="requirementLevel"><option value="MANDATORY">Obligatorio</option><option value="OPTIONAL">Opcional</option></Select></Field><Field label="Orden" htmlFor="sortOrder" required><Input id="sortOrder" name="sortOrder" type="number" defaultValue="0" required /></Field><Button type="submit" loading={addRequirement.isPending} leftIcon={<Plus className="h-4 w-4" />}>Agregar</Button></form></div><div className="panel-card overflow-hidden"><DataTable columns={requirementColumns} data={requirements.data ?? []} keyExtractor={(item) => item.serviceRequirementId} loading={requirements.isLoading} emptyTitle="Sin requisitos" emptyDescription="Este servicio aún no tiene requisitos." /></div></> : <><div className="panel-card mb-5 p-5"><form className="grid gap-4 sm:grid-cols-4" onSubmit={(event) => { event.preventDefault(); addAssignment.mutate(event.currentTarget) }}><Field label="Sucursal" htmlFor="branchId" required><Input id="branchId" name="branchId" type="number" required /></Field><Field label="Área" htmlFor="areaId"><Input id="areaId" name="areaId" type="number" /></Field><Field label="Consultorio" htmlFor="consultingRoomId"><Input id="consultingRoomId" name="consultingRoomId" type="number" /></Field><Field label="Profesional" htmlFor="healthProfessionalId"><Input id="healthProfessionalId" name="healthProfessionalId" type="number" /></Field><Button type="submit" loading={addAssignment.isPending} leftIcon={<Plus className="h-4 w-4" />}>Asignar</Button></form></div><div className="panel-card overflow-hidden"><DataTable columns={assignmentColumns} data={assignments.data ?? []} keyExtractor={(item) => item.serviceAssignmentId} loading={assignments.isLoading} emptyTitle="Sin asignaciones" emptyDescription="Este servicio aún no está asignado." /></div></>}</RelationLayout>
}
