import CatalogCrudPage, { type CatalogCrudConfig } from '@/features/catalogs/CatalogCrudPage'
import { pricingApi } from '@/features/pricing/pricing.api'
import { priceListSchema, specialPriceSchema } from '@/features/pricing/pricing.schemas'
import type { PatientSpecialPrice, PriceList } from '@/features/pricing/pricing.models'
const cell = (item: object, field: string) => String((item as Record<string, unknown>)[field] ?? '-')
const options = (items: Array<[string, string]>) => items.map(([value, label]) => ({ value, label }))
const priceListConfig: CatalogCrudConfig<PriceList> = {
  queryKey: 'price-lists', title: 'Listas de precios', description: 'Administra vigencias, monedas y prioridades de precios.', endpoint: '/price-lists', idField: 'priceListId', filterFields: ['name', 'status'],
  fields: [{ name: 'name', label: 'Nombre', required: true }, { name: 'description', label: 'Descripción', required: true }, { name: 'branchId', label: 'ID de sucursal', type: 'number' }, { name: 'patientCategoryId', label: 'ID de categoría', type: 'number' }, { name: 'currency', label: 'Moneda', required: true }, { name: 'validFrom', label: 'Vigente desde', required: true, type: 'date' }, { name: 'validUntil', label: 'Vigente hasta', type: 'date' }, { name: 'priority', label: 'Prioridad', required: true, type: 'number' }, { name: 'status', label: 'Estado', options: options([['DRAFT', 'Borrador'], ['SCHEDULED', 'Programada'], ['ACTIVE', 'Activa'], ['EXPIRED', 'Expirada'], ['CANCELLED', 'Cancelada']]) }], filterStatusOptions: options([['DRAFT', 'Borrador'], ['SCHEDULED', 'Programada'], ['ACTIVE', 'Activa'], ['EXPIRED', 'Expirada'], ['CANCELLED', 'Cancelada']]),
  schema: priceListSchema, defaultValues: { name: '', description: '', branchId: '', patientCategoryId: '', currency: 'MXN', validFrom: '', validUntil: '', priority: '0', status: 'DRAFT' }, permissions: { read: 'price-lists.read', create: 'price-lists.create', update: 'price-lists.update', archive: 'price-lists.archive' }, list: pricingApi.lists.list, create: pricingApi.lists.create, update: pricingApi.lists.update, remove: pricingApi.lists.remove, getId: (item) => item.priceListId, getCell: cell, detailPath: (item) => `/dashboard/price-lists/${item.priceListId}/details`, toCreateInput: (values) => ({ ...values, branchId: values.branchId ? Number(values.branchId) : undefined, patientCategoryId: values.patientCategoryId ? Number(values.patientCategoryId) : undefined, priority: Number(values.priority) }), toUpdateInput: (values) => ({ ...values, branchId: values.branchId ? Number(values.branchId) : null, patientCategoryId: values.patientCategoryId ? Number(values.patientCategoryId) : null, priority: Number(values.priority) }),
}
const specialPriceConfig: CatalogCrudConfig<PatientSpecialPrice> = {
  queryKey: 'patient-special-prices', title: 'Precios especiales', description: 'Administra precios negociados por paciente y servicio.', endpoint: '/patient-special-prices', idField: 'patientSpecialPriceId', filterFields: ['status'], filterStatusOptions: options([['PENDING', 'Pendientes'], ['APPROVED', 'Aprobados'], ['EXPIRED', 'Expirados'], ['CANCELLED', 'Cancelados']]), fields: [{ name: 'patientId', label: 'ID de paciente', required: true, type: 'number' }, { name: 'serviceId', label: 'ID de servicio', required: true, type: 'number' }, { name: 'branchId', label: 'ID de sucursal', type: 'number' }, { name: 'price', label: 'Precio', required: true }, { name: 'validFrom', label: 'Vigente desde', required: true, type: 'date' }, { name: 'validUntil', label: 'Vigente hasta', type: 'date' }, { name: 'reason', label: 'Motivo' }, { name: 'status', label: 'Estado', options: options([['PENDING', 'Pendiente'], ['APPROVED', 'Aprobado'], ['EXPIRED', 'Expirado'], ['CANCELLED', 'Cancelado']]) }], schema: specialPriceSchema, defaultValues: { patientId: '', serviceId: '', branchId: '', price: '', validFrom: '', validUntil: '', reason: '', status: 'PENDING' }, permissions: { read: 'patient-special-prices.read', create: 'patient-special-prices.create', update: 'patient-special-prices.update', archive: 'patient-special-prices.archive' }, list: pricingApi.specialPrices.list, create: pricingApi.specialPrices.create, update: pricingApi.specialPrices.update, remove: pricingApi.specialPrices.remove, getId: (item) => item.patientSpecialPriceId, getCell: cell, toCreateInput: (values) => ({ ...values, patientId: Number(values.patientId), serviceId: Number(values.serviceId), branchId: values.branchId ? Number(values.branchId) : undefined }), toUpdateInput: (values) => ({ ...values, branchId: values.branchId ? Number(values.branchId) : null }), extraActions: [{ label: 'Aprobar', permission: 'patient-special-prices.approve', when: (item) => item.status === 'PENDING', execute: (item) => pricingApi.specialPrices.approve(item.patientSpecialPriceId).then(() => undefined) }],
}
export function PriceListsPage() { return <CatalogCrudPage config={priceListConfig} /> }
export function SpecialPricesPage() { return <CatalogCrudPage config={specialPriceConfig} /> }
