import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useParams } from 'react-router-dom'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Edit2, Plus, Trash2 } from 'lucide-react'
import { Alert, Button, ConfirmDialog, DataTable, Field, Input, Modal, PageHeader, Select, toast, type DataTableColumn } from '@/components/ui'
import { ApiError } from '@/infrastructure/http'
import { pricingApi } from '@/features/pricing/pricing.api'
import type { PriceListDetail } from '@/features/pricing/pricing.models'
const errorText = (error: unknown) => error instanceof ApiError ? error.messages.join(' ') : error instanceof Error ? error.message : 'No fue posible completar la operación.'
export default function PriceListDetailsPage() {
  const id = Number(useParams().id); const client = useQueryClient(); const [editing, setEditing] = useState<PriceListDetail | null>(null); const [removing, setRemoving] = useState<PriceListDetail | null>(null)
  const query = useQuery({ queryKey: ['price-list-details', id], queryFn: () => pricingApi.lists.details(id), enabled: id > 0 })
  const add = useMutation({ mutationFn: (form: HTMLFormElement) => pricingApi.lists.createDetail(id, { serviceId: Number(new FormData(form).get('serviceId')), price: new FormData(form).get('price')?.toString() ?? '' }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['price-list-details', id] }); toast.success('Detalle agregado.') } })
  const remove = useMutation({ mutationFn: (detailId: number) => pricingApi.lists.removeDetail(id, detailId), onSuccess: () => { void client.invalidateQueries({ queryKey: ['price-list-details', id] }); toast.success('Detalle eliminado.') } })
  const edit = useMutation({ mutationFn: ({ detailId, price, status }: { detailId: number; price: string; status: string }) => pricingApi.lists.updateDetail(id, detailId, { price, status }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['price-list-details', id] }); setEditing(null); toast.success('Detalle actualizado.') } })
  const changeState = useMutation({ mutationFn: (shouldPublish: boolean) => shouldPublish ? pricingApi.lists.publish(id) : pricingApi.lists.unpublish(id), onSuccess: (_, shouldPublish) => { toast.success(shouldPublish ? 'Lista publicada.' : 'Lista retirada de publicación.') } })
  const columns: DataTableColumn<PriceListDetail>[] = [{ key: 'serviceId', header: 'Servicio', cell: (item) => item.serviceId }, { key: 'price', header: 'Precio', cell: (item) => item.price }, { key: 'status', header: 'Estado', cell: (item) => item.status }, { key: 'actions', header: '', align: 'right', cell: (item) => <div className="flex justify-end gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => setEditing(item)}><Edit2 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" title="Eliminar" onClick={() => setRemoving(item)}><Trash2 className="h-4 w-4 text-danger" /></Button></div> }]
  return <div className="page-content"><PageHeader title="Detalles de lista de precios" description="Administra el precio de cada servicio incluido." actions={<Link className="inline-flex h-9 items-center rounded-lg border border-line px-4 text-sm" to="/dashboard/price-lists">Volver</Link>} /><div className="panel-card mb-5 p-5"><form className="flex flex-wrap items-end gap-4" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); add.mutate(event.currentTarget) }}><Field label="ID de servicio" htmlFor="serviceId" required><Input id="serviceId" name="serviceId" type="number" required /></Field><Field label="Precio" htmlFor="price" required><Input id="price" name="price" placeholder="0.00" required /></Field><Button type="submit" loading={add.isPending} leftIcon={<Plus className="h-4 w-4" />}>Agregar</Button><Button type="button" variant="outline" onClick={() => changeState.mutate(true)} loading={changeState.isPending}>Publicar</Button><Button type="button" variant="ghost" onClick={() => changeState.mutate(false)} loading={changeState.isPending}>Despublicar</Button></form>{add.isError && <Alert className="mt-4" variant="danger" title="No se pudo agregar">{errorText(add.error)}</Alert>}</div><div className="panel-card overflow-hidden"><DataTable columns={columns} data={query.data ?? []} keyExtractor={(item) => item.priceListDetailId} loading={query.isLoading} emptyTitle="Sin detalles" emptyDescription="Agrega servicios a esta lista." /></div><ConfirmDialog open={removing !== null} onClose={() => setRemoving(null)} onConfirm={() => { if (removing) { remove.mutate(removing.priceListDetailId); setRemoving(null) } }} loading={remove.isPending} title="¿Eliminar detalle?" description="El servicio dejará de formar parte de esta lista de precios." confirmText="Eliminar" /><Modal open={editing !== null} onClose={() => { if (!edit.isPending) setEditing(null) }} title="Editar detalle" footer={<><Button variant="outline" onClick={() => setEditing(null)}>Cancelar</Button><Button type="submit" form="detail-edit-form" loading={edit.isPending}>Guardar</Button></>}><form id="detail-edit-form" className="grid gap-4" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); edit.mutate({ detailId: editing?.priceListDetailId ?? 0, price: new FormData(event.currentTarget).get('price')?.toString() ?? '', status: new FormData(event.currentTarget).get('status')?.toString() ?? 'ACTIVE' }) }}><Field label="Precio" htmlFor="edit-price" required><Input id="edit-price" name="price" defaultValue={editing?.price ?? ''} required /></Field><Field label="Estado" htmlFor="edit-status" required><Select id="edit-status" name="status" defaultValue={editing?.status ?? 'ACTIVE'}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></Select></Field></form></Modal></div>
}
