export enum PermissionAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  ARCHIVE = 'archive',
  DELETE = 'delete',

  ASSIGN = 'assign',
  UNASSIGN = 'unassign',
  REVOKE = 'revoke',
  APPROVE = 'approve',
  EXPORT = 'export',

  CHANGE_PASSWORD = 'change_password',
  MANAGE_PERMISSIONS = 'manage_permissions',

  CANCEL = 'cancel',
  VOID = 'void',
  ACTIVATE = 'activate',
  DEACTIVATE = 'deactivate',
  CONFIRM = 'confirm',
  CHECK_IN = 'check_in',
  START = 'start',
  COMPLETE = 'complete',
  RESCHEDULE = 'reschedule',
  MARK_NO_SHOW = 'mark_no_show',
  AMEND = 'amend',
  RESTRICT = 'restrict',
  UNRESTRICT = 'unrestrict',
  CLOSE = 'close',
  REOPEN = 'reopen',
  REFUND = 'refund',
  PUBLISH = 'publish',
  UNPUBLISH = 'unpublish',
  BLOCK = 'block',
  UNBLOCK = 'unblock',
  MANAGE_ROLES = 'manage_roles',
  MANAGE_OVERRIDES = 'manage_overrides',
  UPLOAD = 'upload',
  DOWNLOAD = 'download',
  REVOKE_SESSION = 'revoke_session',
}
